#!/usr/bin/env bash
# env_builder.sh — build config.env from environment variables (Koyeb secrets)

set -euo pipefail

# List all keys we want to include (add more if your code expects them)
cat > config.env <<EOF
# auto-generated by env_builder.sh
BOT_TOKEN=${BOT_TOKEN:-}
TELEGRAM_API=${TELEGRAM_API:-}
TELEGRAM_HASH=${TELEGRAM_HASH:-}
FSUB_ID=${FSUB_ID:-}
DUMP_CHAT_ID=${DUMP_CHAT_ID:-}
USER_SESSION_STRING=${USER_SESSION_STRING:-}
EOF

echo "[env_builder] Wrote config.env (first 2 lines):"
head -n 5 config.env

# Now run original start script
if [ -x "./start.sh" ]; then
  exec bash ./start.sh
else
  echo "[env_builder] start.sh not found or not executable. Exiting."
  exit 1
fi
